<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>28dfdf2b-cbbc-4678-bc6b-5fe6c5634512</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.8.0" />
  </ItemGroup>

</Project>
